import dns from 'node:dns'
dns.setServers(['8.8.8.8','8.8.4.4'])

import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";


const josefin = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "WanderLust",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
    
      <body className={`${josefin.className} min-h-full flex flex-col antialiased`}>
        <Navbar />
        <main className="flex-grow">
          {children}
        </main>
              <Toaster />

        <Footer />
      </body>
    </html>
  );
}